FROM centos

RUN yum install -y update

RUN yum install -y epel-release && yum install -y python-pip

RUN pip install flask flask-mysql

#COPY . /opt/source/code

#ENTRYPOINT FLASK_APP=/opt/source-code/app.py flask run
