# create your drupal and postgres config here, based off the last assignment
version: '3'

services:
  custom-drupal:
    build:
      context: .
      dockerfile: drupal.Dockerfile
    ports:
      - '8080:80'
    restart: always
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

  db:
    image: postgres:11.6
    volumes:
      - drupal-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=example

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

#services:
#  cms:
#    image: drupal
#    ports:
#      - '8080:80'
#    volumes:
#      - drupal-modules:/var/www/html/modules
#      - drupal-profiles:/var/www/html/profiles
#     - drupal-sites:/var/www/html/sites
#      - drupal-themes:/var/www/html/themes
#    restart: always
#  db:
#    image: postgres:11.6
#    restart: always
#   environment:
#      - POSTGRES_PASSWORD=example

# volumes:
#  drupal-modules:
#  drupal-profiles:
#  drupal-sites:
#  drupal-themes:

#services:
#  proxy:
#    build:
#      context: .
#      dockerfile: nginx.Dockerfile
#    ports:
#      - '80:80'
#    restart: always

#  web:
#    image: httpd
#    volumes:
#      - ./html:/usr/local/apache2/htdocs/
#    restart: always
